server:
  port: ${port:20000}

spring:
  gray:
    deploy:
      ribbonRule: RandomGrayDeployRule
  application:
    name: zuul-server

# 路由规则配置
zuul:
  #忽略所有默认服务配置
  ignored-services: "*"
  routes:
    product-provider:
      # 这个设置非常关键，要手动设置敏感的请求header, 否则所有请求头都会被过滤，这样设置
      # 主要是为了放行version请求头
      sensitive-headers: Cookie,Set-Cookie,Authorization
      path: /gray_service/**
      stripPrefix: true
      serviceId: product-service-demo3



ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
    healthcheck:
      enabled: true