eureka:
  instance:
    prefer-ip-address: true
    #metadata-map:
    #  version: 1.0.0
  client:
    registerWithEureka: true
    registry-fetch-interval-seconds: 3
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
    healthcheck:
      enabled: true


logging:
  level:
   org.springframework.web.servlet.DispatcherServlet: DEBUG