spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        # 使用了spring-boot-starter-actuator 的地址
        # 使用默认的就好 actuator/health， 因为会自动提取该路径
        # healthCheckPath: ${management.server.servlet.context-path}"/health"
        healthCheckInterval: 15s
        instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
        # prefer-agent-address: false
        tags:
          - DEMO1服务
          - 基础层服务
        #  - version=1.0.0
        instance-group: 测试环境
        management-tags: 管理Tag
        query-passing: true
        prefer-ip-address: true
        default-zone-metadata-name: 张雪友
        #heartbeat:
          #enabled: true
          #ttl-value: 60
