# demo配置服务名

gray:
  title: 基础层服务正式版本1
  #title: 基础层服务灰度版本

server:
  port: ${port:31000}

spring:
  application:
    name: base-demo1-service
  sleuth:
    sampler:
      probability: 1.0
    hystrix:
      strategy:
        enabled: false
  zipkin:
    sender:
      type: web
    base-url: http://127.0.0.1:9411/
    enabled: true
    discovery-client-enabled: false


rabbitmq:
  host: 127.0.0.1
  port: 5672
  username: guest
  password: guest

logging:
  level:
   org.springframework.web.servlet.DispatcherServlet: DEBUG



