spring:
  application:
    name: eureka-server

server:
  port: 8080

eureka:
  instance:
      prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: false
    service-url:
        defaultZone: http://localhost:8080/eureka
