
eureka:
  instance:
    prefer-ip-address: true
    #metadataMap:
    #  version: 1.0.0
  client:
    registerWithEureka: true
    registry-fetch-interval-seconds: 30
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
    healthcheck:
      enabled: true