
eureka:
  instance:
    prefer-ip-address: true
    metadataMap:
      version: ${spring.gray.deploy.version:}
  client:
    registerWithEureka: true
    registry-fetch-interval-seconds: 30
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8766/eureka/
    healthcheck:
      enabled: true